apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2022-07-08T04:24:59Z"
  labels:
    app: nginx-dep
  name: nginx-service
  namespace: default
  resourceVersion: "243181"
spec:
  clusterIP: 10.109.153.244
  clusterIPs:
  - 10.109.153.244
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: nginx-dep
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
