apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2022-07-08T02:09:42Z"
  labels:
    app: nginx
  name: nginx
  namespace: default
  resourceVersion: "222004"
  uid: 0d69f769-b45a-4bb2-b68c-7b446e8fe4a0
spec:
  clusterIP: 10.100.235.81
  clusterIPs:
  - 10.100.235.81
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - port: 80
    protocol: TCP
  selector:
    app: nginx
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
